#!/bin/bash

flatpak_apps=(
  "io.gitlab.librewolf-community"
  "com.brave.Browser"
  "org.qbittorrent.qBittorrent"
  "org.nicotine_plus.Nicotine"
  "org.kde.elisa"
  "com.github.tchx84.Flatseal"
)

flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

for app in ${flatpak_apps[@]}; do
  flatpak install --user -y $app
done
