#!/bin/bash

if [ ! -d ".git/" ]; then
  printf "Not in dot-files root dir"
  exit 1
fi

config_files=("alacritty" "gallery-dl" "mpv" "nvim" "picom" "qtile" "ranger" "rofi" "yt-dlp" "zathura")


for i in "${config_files[@]}"
do
  cp $HOME/.config/$i ./.config/ -r
done


cp $HOME/.bashrc .
cp $HOME/.xinitrc .

cp -r $HOME/Pictures/Wallpapers/* ./Pictures/Wallpapers/

git add .
git commit -m "update dots"
git push origin main
