#!/bin/bash

## Copy all relevant files
if [ ! -d "$HOME/.config/" ]; then
  mkdir -p "$HOME/.config/"
fi
cp -r ./.config/* "$HOME/.config/"

if [ ! -d "$HOME/.local/bin" ]; then
  mkdir -p "$HOME/.local/bin/"
fi
cp -r ./.local/bin/* "$HOME/.local/bin/"

cp -r "Pictures/" "$HOME/Pictures"


## Install all packages
void_packages=(
  # System
  opendoas curl
  # Xorg
  xorg-server libX11 xorg-input-drivers nvidia xinit
  # Desktop
  qtile alacritty mpv ffmpeg picom feh ranger rofi xset feh zathura flatpak
  scrot
  # dbus
  dbus dbus-devel dbus-glib dbus-x11
  # Audio
  pipewire wireplumber
  # Scraping
  gallery-dl yt-dlp python3-BeautifulSoup4 python3-requests python3-pip
  python3-pipx
  # Neovim
  neovim python3-lsp-server
  # Other
  lsd rsync
)

sudo xbps-install -Syu
sudo xbps-install -y void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree
sudo xbps-install -S
sudo xbps-install -Sy ${void_packages[@]}

sudo echo "permit :wheel" > /etc/doas.conf


flatpak_apps=(
  "io.gitlab.librewolf-community"
  "com.brave.Browser"
  "org.qbittorrent.qBittorrent"
  "org.nicotine_plus.Nicotine"
  "org.kde.elisa"
  "com.github.tchx84.Flatseal"
)

for i in ${flatpak_apps[@]}
do
  flatpak install --user -y $i
done
