#!/bin/bash


read -p "Type yes in capitals to install the dot-files: " yes
if [[ "$yes" != "YES" ]]; then
  exit
fi

## Copy all relevant files
if [ ! -d "$HOME/.config/" ]; then
  mkdir -p "$HOME/.config/"
fi
cp -r ./.config/* "$HOME/.config/"

if [ ! -d "$HOME/.local/bin" ]; then
  mkdir -p "$HOME/.local/bin/"
fi
cp -r ./.local/bin/* "$HOME/.local/bin/"

cp -r "Pictures/" "$HOME/Pictures"
cp .bashrc $HOME/
cp .xinitrc $HOME/


## Install all packages
void_packages=(
  # System
  opendoas curl unzip
  # Xorg
  xorg-server libX11 xorg-input-drivers nvidia xinit
  # Desktop
  qtile alacritty mpv ffmpeg picom feh ranger rofi xset feh zathura flatpak
  scrot xdg-desktop-portal xdg-desktop-portal-gtk python3-psutil
  # dbus
  dbus dbus-devel dbus-glib dbus-x11 xdg-dbus-proxy dbus-glib dbus-x11
  # Audio
  pipewire wireplumber pulseaudio
  # Scraping
  gallery-dl yt-dlp python3-BeautifulSoup4 python3-requests python3-pip
  python3-pipx python3-lxml
  # Neovim
  neovim python3-lsp-server
  # Other
  lsd rsync elogind rtkit polkit pnpm xauth
)

sudo xbps-install -Syu
sudo xbps-install -y void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree
sudo xbps-install -S
sudo xbps-install -Sy ${void_packages[@]}

echo "permit :wheel" | sudo tee -a /etc/doas.conf

services=(
  "dbus"
  "elogind"
  "polkitd"
  "rtkit"
)

for service in ${services}; do
  if [[ ! -L /var/service/$service/ ]]; then
    sudo ln -s /etc/sv/$service/ /var/service/
  fi
done

sudo ln -s /etc/sv/dbus/ /var/service/
sudo ln -s /etc/sv/elogind/ /var/service/
sudo ln -s /etc/sv/polkitd/ /var/service/
sudo ln -s /etc/sv/rtkit/ /var/service/

# install Jetbrains
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
