#!/bin/bash

## Install all packages
void_packages=(
  # System
  opendoas curl unzip bash-completion python3-virtualenv
  # Xorg
  xorg-server libX11 xorg-input-drivers nvidia xinit
  # Desktop
  qtile alacritty mpv ffmpeg picom feh ranger rofi xset feh zathura zathura-pdf-mupdf
  flatpak scrot xdg-desktop-portal xdg-desktop-portal-gtk python3-psutil dunst
  # dbus
  dbus dbus-devel dbus-glib dbus-x11 xdg-dbus-proxy dbus-glib dbus-x11
  # Audio
  pipewire wireplumber pulseaudio playerctl
  # Scraping
  gallery-dl yt-dlp python3-BeautifulSoup4 python3-requests python3-pip
  python3-pipx python3-lxml
  # Neovim
  neovim python3-lsp-server
  # Other
  lsd rsync elogind rtkit polkit pnpm xauth ripgrep
)

sudo xbps-install -Syu
sudo xbps-install -y void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree
sudo xbps-install -S
sudo xbps-install -Sy ${void_packages[@]}


services=(
  "dbus"
  "elogind"
  "polkitd"
  "rtkit"
)

for service in "${services[@]}"; do
  if [[ ! -L "/var/service/$service/" ]]; then
    sudo ln -s /etc/sv/$service/ /var/service/
  fi
done
