{
  "main-fg": "#f7dba4",
  "post-bg": "#282828",
  "border": "#a28e72",
  "second-bg": "#282828",
  "grey": "#837366",
  "placeholder": "#8373669e",
  "purple": "#b16286",
  "red": "#ff4c3c",
  "orange": "#fc802d",
  "yellow": "#d79921",
  "green": "#95bd77",
  "blue": "#458588",
  "turquoise": "#83a598",
  "light-blue": "#83a598"
}
bar_bg: #3c3836
bar_fg: #f7dba4
border: #b16286
workspace_norm: #458588
workspace_active: #b16286
focused: #95bd77 
unfocused: #282828
