[cursor.style]
# shape = "Block"
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 100000

[window.padding]
x = 15
y = 10

[window]
dynamic_title = false
